### ISSUE TITLE
Consider using Task/IO instead of Id

### ISSUE THREAD

**Issue by jdegoes** [notxcain/onion-architecure#1]
I'd suggest using Monix `Task` or other IO-like monad for the final interpretation, to preserve referential transparency until the end of the world.

Otherwise, looks great! 👍

**Comment by jdegoes** [comment]
Also if you want a quick & dirty IO, you can use this one:

https://gist.github.com/jdegoes/97459c0045f373f4eaf126998d8f65dc

**Comment by notxcain** [comment]
@jdegoes thanks! Yeah, I thought about that, I didn't want to add other dependencies to the example. I'll add Monix or fs2 later :) What do you think about this [`.unhalt`](https://github.com/notxcain/onion-architecure/blob/master/src/main/scala/onion/example.scala#L102) hack? Is it doable any other way?

**Comment by jdegoes** [comment]
That's not a hack — what you're doing there is ignoring the `A` which the halting logger will never return, by replacing it with a unit (which the halting logger can / does return). Though I might rename it to `continue` or `ignore` or something like that (though `unhalt` isn't a bad name, it just doesn't convey the idea that the resumption of the program occurs by ignoring the `A`).

By the way, does `Halt` really need to have a `Functor` instance? I couldn't see where this is used.

**Comment by notxcain** [comment]
The name was chosen to show that it unlifts `F[_]` from `Halt`, i.e. unhalts 😃. I like `ignore` though, or maybe `ignoreResult`.

Regarding `Halt` being a `Functor`. Yes, `Free[F, A]#fold` has signature `def fold[B](r: A => B, s: F[Free[F, A]] => B)(implicit F: Functor[F]): B`.

**Comment by jdegoes** [comment]
Ah, OK, that makes sense.

Again, nice work! I will link to this repo from my blog article. 😄
